name: Build and Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 4

    - name: Run tests directly
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          ./build/${{ matrix.build_type }}/tests.exe
        else
          ./build/tests
        fi
